# Generated by Django 3.0.1 on 2019-12-20 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(blank=True, max_length=250, null=True)),
                ('vendor', models.CharField(blank=True, max_length=300, null=True)),
                ('mrp', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('batch_number', models.CharField(blank=True, max_length=250, null=True)),
                ('batch_date', models.DateField(blank=True, null=True)),
                ('quantity', models.FloatField(blank=True, null=True)),
                ('status', models.IntegerField(blank=True, choices=[(0, 'Pending'), (1, 'Approved')], default=0, null=True)),
            ],
        ),
    ]
